In [1]:
import numpy as np

In [8]:
a=np.array([[1,0,1],[0,0,0],[-1,0,-1]])

In [9]:
a

array([[ 1,  0,  1],
       [ 0,  0,  0],
       [-1,  0, -1]])

In [11]:
a@a

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [12]:
a@a@a

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [17]:
b=np.array([[1,0,-1]])

In [18]:
b

array([[ 1,  0, -1]])

In [19]:
b.T

array([[ 1],
       [ 0],
       [-1]])

In [21]:
b.T.T

array([[ 1,  0, -1]])

In [23]:
A=b.T@b.T.T

In [24]:
A

array([[ 1,  0, -1],
       [ 0,  0,  0],
       [-1,  0,  1]])

In [25]:
A@A

array([[ 2,  0, -2],
       [ 0,  0,  0],
       [-2,  0,  2]])

In [26]:
A@A@A

array([[ 4,  0, -4],
       [ 0,  0,  0],
       [-4,  0,  4]])

In [27]:
A@A@A@A

array([[ 8,  0, -8],
       [ 0,  0,  0],
       [-8,  0,  8]])

In [44]:
a=np.array([[0,-1,0],[1,0,0],[0,0,-1]])

In [45]:
a

array([[ 0, -1,  0],
       [ 1,  0,  0],
       [ 0,  0, -1]])

In [46]:
a@a

array([[-1,  0,  0],
       [ 0, -1,  0],
       [ 0,  0,  1]])

In [48]:
a@a@a@a

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [49]:
I=np.eye(a.shape[0])

In [50]:
I-2*a@a

array([[ 3.,  0.,  0.],
       [ 0.,  3.,  0.],
       [ 0.,  0., -1.]])

In [1]:
import torch
import torch.nn as nn
import torchvision.models as models
import torch.optim as optim

In [2]:
class ResNetModel(nn.Module):
    def __init__(self, num_classes=7):
        super(ResNetModel, self).__init__()
        # 加载预训练的 ResNet50
        self.resnet = models.resnet18(pretrained=False)
        # 修改全连接层输出为7类情感
        self.resnet.fc = nn.Linear(self.resnet.fc.in_features, num_classes)

    def forward(self, x):
        return self.resnet(x)


In [6]:
model_vision = torch.load("sentiment_web/model-64-unpretrained.pth", map_location=torch.device('cpu'), weights_only=False)


In [5]:
model_vision.eval()

ResNetModel(
  (resnet): ResNet(
    (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
    (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (relu): ReLU(inplace=True)
    (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
    (layer1): Sequential(
      (0): BasicBlock(
        (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu): ReLU(inplace=True)
        (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (1): BasicBlock(
        (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_

In [10]:
from mtcnn import MTCNN
import cv2

# 创建 MTCNN 检测器
detector = MTCNN()

# 读取图像
img = cv2.imread('your_image.jpg')

# 使用 MTCNN 检测人脸
faces = detector.detect_faces(img)

# 绘制检测到的人脸框
for face in faces:
    x, y, width, height = face['box']
    cv2.rectangle(img, (x, y), (x + width, y + height), (0, 255, 0), 2)

cv2.imshow('Face Detection', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

ModuleNotFoundError: No module named 'tensorflow'

In [9]:
!pip install tensorflow

Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/fb/59/3eb58629e3749d9f4fc1e522487af369f9bd4c451f465d3054961fab6bf8/tensorflow-2.13.1-cp38-cp38-win_amd64.whl (1.9 kB)
INFO: pip is looking at multiple versions of tensorflow to determine which version is compatible with other requirements. This could take a while.
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/5b/6f/8b125d126d54061c0be610b135aaf2f8960f55c2e185ac32445e4a5012d5/tensorflow-2.13.0-cp38-cp38-win_amd64.whl (1.9 kB)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/38/ba/dd4d998a852451e98dc009ecb208bbb0eeb0c8252dc35b7c4e1050762b36/tensorflow_intel-2.13.0-cp38-cp38-win_amd64.whl (276.5 MB)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/a2/ad/e0d3c824784ff121c03cc031f944bc7e139a8f1870ffd2845cc2dd76f6c4/absl_py-2.1.0-py3-none-any.whl (133 kB)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/2b/03/13dde6512ad7b4557eb792fbcf0

ERROR: Could not install packages due to an OSError: [WinError 5] 拒绝访问。: 'C:\\Users\\30813\\Desktop\\sentiment_web\\.venv\\Lib\\site-packages\\numpy\\.libs\\libopenblas64__v0.3.21-gcc_10_3_0.dll'
Check the permissions.


[notice] A new release of pip is available: 23.2.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip
