In [1]:
print("Hello,World")

Hello,World


In [2]:
import numpy as np

In [5]:
# 创建矩阵
A = np.array([[1, 2], 
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

In [13]:
A

array([[1, 2],
       [3, 4]])

In [9]:
B

array([[5, 6],
       [7, 8]])

In [12]:
C=A+B
C

array([[ 6,  8],
       [10, 12]])

In [14]:
C=A-B
C

array([[-4, -4],
       [-4, -4]])

In [15]:
# 逐元素乘法(只有矩阵大小相同时才能进行此操作）
C=A*B
C

array([[ 5, 12],
       [21, 32]])

In [16]:
# 矩阵乘法2*2 2*2 -> 2*2
C=A@B
C

array([[19, 22],
       [43, 50]])

In [17]:
C=A.T
C

array([[1, 3],
       [2, 4]])

In [25]:
# 计算行列式
det_A=np.linalg.det(B)
round(det_A,10)

-2.0

In [27]:
inv_A=np.linalg.inv(A)
inv_A

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [30]:
E=np.array([[4,-2],[1,1]])

In [31]:
eigvals,eigvecs=np.linalg.eig(E)
eigvals,eigvecs

(array([3., 2.]),
 array([[0.89442719, 0.70710678],
        [0.4472136 , 0.70710678]]))

In [33]:
rank_A=np.linalg.matrix_rank(A)
rank_A

2

In [36]:
trace_A=np.trace(A)
trace_A

5

In [37]:
norm_A=np.linalg.norm(A)
norm_A

5.477225575051661

In [38]:
H_stack=np.hstack((A,B))
H_stack

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [40]:
V_stack=np.vstack((A,B))
V_stack

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [41]:
30**0.5

5.477225575051661